spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:15432/cvr-db
    username: username
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  error:
    include-message: always
logging:
  level:
    com.cebrailerdogan.cvrservice: DEBUG