spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://esekyuku:49153/cvr-db
    username: user
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  error:
    include-message: always