spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://esekyuku:49153/cvr-db
    username: user
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.springframework.web.client.RestTemplate: TRACE
server:
  error:
    include-message: always